### ISSUE TITLE
not found in `image'

### ISSUE THREAD

**Issue by rollysys** [tversteeg/distance-field#14]
So sorry  that i'm not familiar with rust so maybe this is a rather stupid question.
I just got error when run the command listed in readme:
error[E0425]: cannot find function, tuple struct or tuple variant `ImageLuma8` in crate `image`
  --> examples/generator.rs:37:12
   |
37 |     image::ImageLuma8(outbuf).save(args.get_str("<dest>")).unwrap();
   |            ^^^^^^^^^^ not found in `image`
   |
help: consider importing this tuple variant
   |
5  | use image::DynamicImage::ImageLuma8;
   |

For more information about this error, try `rustc --explain E0425`.

Please help and many thanks!

**Comment by tversteeg** [comment]
Thanks for the bug report, I haven't been maintaining this repository for a while now, what is your intended purpose with it if you don't mind me asking?
